#' Read NY voter file
#'
#' @param path path to NY voter file
#' @param ... additional arguments passed to `readr::read_csv()`
#'
#' @return tibble
#' @export
#'
#' @examples
#' # TODO
vf_read_ny <- function(path, ...) {

  if (missing(path)) {
    cli::cli_abort('Must specify {.arg path}.')
  }

  readr::read_csv(
    file = path,
    col_names = ny_names,
    col_types = readr::cols(
      name_last                        = readr::col_character(),
      name_first                       = readr::col_character(),
      name_middle                      = readr::col_character(),
      name_suffix                      = readr::col_character(),
      residence_address_number         = readr::col_character(),
      residence_address_half_code      = readr::col_character(),
      residence_address_pre_direction  = readr::col_character(),
      residence_street_name            = readr::col_character(),
      residence_address_post_direction = readr::col_character(),
      residence_address_unit_type      = readr::col_character(),
      residence_address_unit_number    = readr::col_character(),
      residence_address_nonstandard    = readr::col_character(),
      residence_city                   = readr::col_character(),
      residence_zipcode                = readr::col_double(),
      residence_zipcode_plus4          = readr::col_double(),
      mailing_address_line_1           = readr::col_character(),
      mailing_address_line_2           = readr::col_character(),
      mailing_address_line_3           = readr::col_character(),
      mailing_address_line_4           = readr::col_character(),
      birth_date                       = readr::col_double(),
      gender                           = readr::col_character(),
      party_affiliation                = readr::col_character(),
      other_party_affiliation          = readr::col_character(),
      county                           = readr::col_double(),
      election_district                = readr::col_double(),
      legislative_district             = readr::col_double(),
      city                             = readr::col_character(),
      ward                             = readr::col_character(),
      congressional_district           = readr::col_double(),
      senate_district                  = readr::col_double(),
      assembly_district                = readr::col_double(),
      last_voted_date                  = readr::col_double(),
      last_voted_year                  = readr::col_double(),
      last_voted_county                = readr::col_double(),
      last_voted_address               = readr::col_character(),
      last_voted_name                  = readr::col_character(),
      county_voter_registration_number = readr::col_character(),
      registration_date                = readr::col_double(),
      voter_application_source         = readr::col_character(),
      voter_id_required                = readr::col_character(),
      voter_id_requirement_met         = readr::col_character(),
      voter_status                     = readr::col_character(),
      voter_status_reason              = readr::col_character(),
      inactive_date                    = readr::col_double(),
      purge_date                       = readr::col_double(),
      voter_id                         = readr::col_character(),
      voter_history                    = readr::col_character()
    ),
    ...
  )
}

ny_names <- c(
  'name_last',
  'name_first',
  'name_middle',
  'name_suffix',
  'residence_address_number',
  'residence_address_half_code',
  'residence_address_pre_direction',
  'residence_street_name',
  'residence_address_post_direction',
  'residence_address_unit_type',
  'residence_address_unit_number',
  'residence_address_nonstandard',
  'residence_city',
  'residence_zipcode',
  'residence_zipcode_plus4',
  'mailing_address_line_1',
  'mailing_address_line_2',
  'mailing_address_line_3',
  'mailing_address_line_4',
  'birth_date',
  'gender',
  'party_affiliation',
  'other_party_affiliation',
  'county',
  'election_district',
  'legislative_district',
  'city',
  'ward',
  'congressional_district',
  'senate_district',
  'assembly_district',
  'last_voted_date',
  'last_voted_year',
  'last_voted_county',
  'last_voted_address',
  'last_voted_name',
  'county_voter_registration_number',
  'registration_date',
  'voter_application_source',
  'voter_id_required',
  'voter_id_requirement_met',
  'voter_status',
  'voter_status_reason',
  'inactive_date',
  'purge_date',
  'voter_id',
  'voter_history'
)

ny_county_codes <- tibble::tribble(
  ~county, ~county_code,
  'Albany', '01',
  'Allegany', '02',
  'Bronx', '03',
  'Broome', '04',
  'Cattaraugus', '05',
  'Cayuga', '06',
  'Chautauqua', '07',
  'Chemung', '08',
  'Chenango', '09',
  'Clinton', '10',
  'Columbia', '11',
  'Cortland', '12',
  'Delaware', '13',
  'Dutchess', '14',
  'Erie', '15',
  'Essex', '16',
  'Franklin', '17',
  'Fulton', '18',
  'Genesee', '19',
  'Greene', '20',
  'Hamilton', '21',
  'Herkimer', '22',
  'Jefferson', '23',
  'Kings', '24',
  'Lewis', '25',
  'Livingston', '26',
  'Madison', '27',
  'Monroe', '28',
  'Montgomery', '29',
  'Nassau', '30',
  'New York', '31',
  'Niagara', '32',
  'Oneida', '33',
  'Onondaga', '34',
  'Ontario', '35',
  'Orange', '36',
  'Orleans', '37',
  'Oswego', '38',
  'Otsego', '39',
  'Putnam', '40',
  'Queens', '41',
  'Rensselaer', '42',
  'Richmond', '43',
  'Rockland', '44',
  'Saratoga', '45',
  'Schenectady', '46',
  'Schoharie', '47',
  'Schuyler', '48',
  'Seneca', '49',
  'St.Lawrence', '50',
  'Steuben', '51',
  'Suffolk', '52',
  'Sullivan', '53',
  'Tioga', '54',
  'Tompkins', '55',
  'Ulster', '56',
  'Warren', '57',
  'Washington', '58',
  'Wayne', '59',
  'Westchester', '60',
  'Wyoming', '61',
  'Yates', '62'
)

ny_voting_methods <- c(
  'P' = 'Election Day Poll Site',
  'A' = 'Absentee',
  'F' = 'Election Day Affidavit',
  'O' = 'Election Day by Other Method',
  'E' = 'Early Voting at Poll Site (Early voting method introduced in General Election 2019)',
  'D' = 'Early Voting by Affidavit (Early voting method introduced in General Election 2019)',
  'T' = 'Early Voting by Other Method (Early voting method introduced in General Election 2019)'
)
